### ISSUE TITLE
need for pgcrypto in linux alpine binaries

### ISSUE THREAD

**Issue by ptitcoutu** [zonkyio/embedded-postgres-binaries#1]
I use embedded postgres to test my application and it works well on mac but not on linux alpine because pgcrypto is not available in this configuration.
What can I do to be able to use pgcrypto even in linux alpine ?

**Comment by tomix26** [comment]
Maybe it is because the alpine version is compiled without the `--with-openssl` parameter.
I'll check it out and fix it. Thanks for the report.

**Comment by tomix26** [comment]
@ptitcoutu What functions and algorithms are you using? Because most of standard algorithms should be built-in.

**Comment by tomix26** [comment]
I've already found the probable cause of the problem. The `pgcrypto` is part of additionally supplied modules and this is written in the official documentation:

> When building from the source distribution, these components are not built automatically, unless you build the "world" target

Link: https://www.postgresql.org/docs/current/static/contrib.html

**Comment by tomix26** [comment]
Fixed versions 9.3.24-1, 9.4.19-1, 9.5.14-1, 9.6.10-1, 10.5.0-1 have been released.
