### ISSUE TITLE
Working with uuid extension issue

### ISSUE THREAD

**Issue by vladimiravramov** [zonkyio/embedded-postgres-binaries#13]
Hello!

I've stuck with uuid extension issue. Adding uuid extension is not allowed. If your script has line like this 
`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`
You've got the error. This is because there're no `libossp-uuid.so.16` library in the bundled postgresql. Please, add this and it will work fine.

**Comment by tomix26** [comment]
Thanks for the report.
