### ISSUE TITLE
Make Darwin bundle fully self-contained by including libpq

### ISSUE THREAD

**Issue by glasser** [zonkyio/embedded-postgres-binaries#17]
I don't use your fork but it looks nice. I prepared a PR for the upstream but it looks like your fork has the same issue. Fortunately it's a one line fix.

Full details at https://github.com/opentable/otj-pg-embedded/pull/135 but the gist is that `bin/initdb` links to the PG C client `libpq` but the repack scripts don't include that library. It mostly works because OSX comes with some version of libpq but the results aren't as embedded as you would like!

**Comment by tomix26** [comment]
Thanks for the report. I will take a look at it and fix it.
