### ISSUE TITLE
Include psql and pg_restore executables

### ISSUE THREAD

**Issue by ketronkowski** [zonkyio/embedded-postgres-binaries#19]
Would it be possible to include the psql and pg_restore executables in the bundle?

We are looking to put together some schema/data migration tests from know database states and are struggling to figure out how to seed the embedded database without the tools.

Thanks!

**Comment by tomix26** [comment]
In my opinion, the bundle should contain only executables needed to run the database. If the `psql` and `pg_restore` executables were included into the bundle, the resulting size would be about 1MB larger and not everyone needs it.

So I would rather you solve this problem in some other way. For example, using Flyway migration tool or, if you are using [embedded-database-spring-test](https://github.com/zonkyio/embedded-database-spring-test) library, using [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) and baking the data with database states into a docker image.

Are these solutions acceptable to you?

**Comment by ketronkowski** [comment]
Thanks for getting back to me and the rationale for not already including the commands. 

The tests that we would like to run _are_ actually testing our liquibase schema migrations (including custom migrators that programmatically manipulate data already existing in the DB).

If having at least the psql tool included is not an option we could certainly give the docker provider a shot. 

Thanks again!
