### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by uschi2000** [zonkyio/embedded-postgres-binaries#42]
I'm trying to use embedded-postgres-binaries via Rust's pg-embed crate on an Apple Silicon laptop. It looks like this requires a build for darwin/arm64v8 which does seem to exist. Would be great to have this!

**Comment by tomix26** [comment]
I would like it too, but I'm still waiting for EnterpriseDB to release binaries for M1 architecture. More information there: https://github.com/zonkyio/embedded-postgres/issues/52

**Comment by tomix26** [comment]
@uschi2000 As a temporary solution it's possible to use Rosetta 2 emulation for this case. But it requires a change to the rust `pg-embed` library. There is an example from java `embedded-postgres` library there: https://github.com/zonkyio/embedded-postgres/commit/ce6256ea4fced93b378a0f92cdc54f92a35b80cc

**Comment by hgschmie** [comment]
The 14.x binaries that you have released are actually "fat" binaries, so they contain both amd64 and aarch64 code. Simplest solution going forward would be to release these both as amd64 and aarch64. I have not checked the latest releases for older versions.
