### ISSUE TITLE
releasing newer versions

### ISSUE THREAD

**Issue by hgschmie** [zonkyio/embedded-postgres-binaries#43]
Hi,

Do you have plans to release newer versions of the postgres binaries (10.19, 11.14, 12.9, 13.5, 14.1)? Especially 14.1 would be great as this contains 'fat' binaries for MacOS (IAW they run natively on the M1). 

-h

**Comment by tomix26** [comment]
Hi, thanks for the information. I'm going to release it the new week, because there is a problem with the build pipeline (https://github.com/zonkyio/embedded-postgres-binaries/pull/44).

**Comment by hgschmie** [comment]
I noticed that you closed this issue, however I did not see newer binaries on Maven Central. 13.4.0 is still the latest released version.

**Comment by tomix26** [comment]
Yep, I'm working on that, there are some troubles with the release.

**Comment by tomix26** [comment]
@hgschmie The new versions have been released.
