### ISSUE TITLE
Include `pg_dump` and `pg_restore` into the packaged archives

### ISSUE THREAD

**Issue by binaek** [zonkyio/embedded-postgres-binaries#52]
As `postgresql` advances through major versions, it is impossible to use the `data-dir` from a previous version in the new version. Including the `pg_dump` and `pg_restore` will help in transferring data to the new version

**Comment by tomix26** [comment]
The goal of this project is to provide lightweight bundles of postgres binaries for testing purposes. So there shouldn't be a need to migrate the data between different versions of postgres. If so, you are probably using it for a different purpose than intended. There is a similar issue with maybe a slightly better explanation here: https://github.com/zonkyio/embedded-postgres-binaries/issues/19
