### ISSUE TITLE
MacOS arm64 binaries for 10, 11, 12, 13 do not contain arm64 binaries and require rosetta.

### ISSUE THREAD

**Issue by hgschmie** [zonkyio/embedded-postgres-binaries#58]
The following embedded-postgres-binaries-darwin-arm64v8-x.y.z.jar archives do not actually contain arm64v8 binaries:

(tested with 
```
jar xf embedded-postgres-binaries-darwin-arm64v8-10.20.0.jar
tar xjf postgres-darwin-arm_64.txz
file bin/postgres
```
)

- 10.20.0 (contains x86_64 and i386)
- 11.15.0  (contains x86_64)
- 12.10.0 (contains x86_64)
- 13.6.0 (contains x86_64)

all released 14.x versions are ok (contain both x86_64 and arm64)

as a result, none of these binaries actually work on an arm64 mac unless rosetta is installed.

**Comment by hgschmie** [comment]
(tested on a AWS mac2 instance with and without rosetta installed)

**Comment by tomix26** [comment]
Yes, it's known issue, I described it here: https://github.com/zonkyio/embedded-postgres/issues/86#issuecomment-1120425822
