### ISSUE TITLE
Postgres binary of version 14.10.0 does not work on Mac

### ISSUE THREAD

**Issue by e-wag** [zonkyio/embedded-postgres-binaries#75]
As version 14.10.0 is the new default one since https://github.com/zonkyio/embedded-postgres/pull/123, we noticed this issue.

The following error occurs:

```text
/var/folders/s1/1jm7mb_j6jqgtq78f24h5b280000gp/T/embedded-pg/PG-f15761a1c59ff5f8349c12c01b3af539/bin/initdb -A trust -U postgres -D /var/folders/s1/1jm7mb_j6jqgtq78f24h5b280000gp/T/epg4423307102381004501 -E UTF-8
dyld[2295]: Library not loaded: @loader_path/../lib/libintl.8.dylib
  Referenced from: <2023A287-FF50-3D03-8AF9-D2783EDBED04> /private/var/folders/s1/1jm7mb_j6jqgtq78f24h5b280000gp/T/embedded-pg/PG-f15761a1c59ff5f8349c12c01b3af539/lib/libgssapi_krb5.2.2.dylib
  Reason: tried: '/private/var/folders/s1/1jm7mb_j6jqgtq78f24h5b280000gp/T/embedded-pg/PG-f15761a1c59ff5f8349c12c01b3af539/lib/../lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
```

I've tried out versions 14.8.0, 14.9.0, 15.0.0, and 16.0.0 as well. Those seem to work fine.

**Comment by patrickhuy** [comment]
I'm seeing the same issue on M1 Mac. The problem seems to happen both when using the Linux AMD64 binaries as well as when using the darwin arm64v8 binaries

**Comment by tomix26** [comment]
Thank you guys for the report. I'll take a look at it as soon as possible.

Do you have any extensions enabled that could be causing this problem? Because the tests passed successfully during the release.

@patrickhuy Are you sure? Because this problem typically occurs only on the MacOS platform. Could you please attach an example of the error that you are experiencing?

**Comment by tomix26** [comment]
@patrickhuy Ok, great, thank you for the clarification.

**Comment by e-wag** [comment]
@tomix26 Thank you for looking into this issue.

> Do you have any extensions enabled that could be causing this problem?

Not as far as I know. 

It seems odd that all the other listed binaries I've tried worked. When I check the `libs` folder of the other downloaded binaries, I can see that they don't include `libgssapi_krb5.2.2.dylib` which seems to cause the issue. If I can provide you with any more information, feel free to reach out.

**Comment by tomix26** [comment]
The bugfix versions have been released. Thanks again for reporting the problem.
