### ISSUE TITLE
Feat: ICU Support

### ISSUE THREAD

**Issue by c-thiel** [zonkyio/embedded-postgres-binaries#86]
We are using case insensitive collations defined as:

```sql
    CREATE COLLATION case_insensitive (
      provider = icu,
      locale = 'und-u-ks-level2',
      deterministic = false
    )
 ```
 
 Which currently raises: 
 ```
ICU is not supported in this build
```

Would it be possible to add ICU-support for the binaries?

**Comment by tomix26** [comment]
Hey @c-thiel, thanks for the report. ICU support should already be included. What exact version of the binaries are you using? Postgres version, platform, etc. Also, check that you are not using the lite version of the binaries, as it doesn't include ICU on purpose to reduce file size.

**Comment by c-thiel** [comment]
@tomix26 you are right, apparently I configured my embedded postgres dependency in rust wrong. Thanks!
